<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['num_links']       = 10;
$config['full_tag_open']   = '<div class="pagination"><ul>';
$config['full_tag_close']  = '</ul></div>';
$config['first_link']      = '&laquo;';
$config['first_tag_open']  = '<li>';
$config['first_tag_close'] = '</li>';
$config['last_link']       = '&raquo;';
$config['last_tag_open']   = '<li>';
$config['last_tag_close']  = '</li>';
$config['next_link']       = '&raquo;';
$config['next_tag_open']   = '<li>';
$config['next_tag_close']  = '</li>';
$config['prev_link']       = '&laquo;';
$config['prev_tag_open']   = '<li>';
$config['prev_tag_close']  = '</li>';
$config['cur_tag_open']    = '<li class="active"><a>';
$config['cur_tag_close']   = '</a></li>';
$config['num_tag_open']    = '<li>';
$config['num_tag_close']   = '</li>';