<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['num_links']       = 8;
$config['first_link']      = 'First';
$config['full_tag_open']   = '<div class="pagination"><ul>';
$config['full_tag_close']  = '</ul></div>';
$config['first_link']      = '<a></a>';
$config['first_tag_open']  = '<li class="first">';
$config['first_tag_close'] = '</li>';
$config['last_link']       = '<a></a>';
$config['last_tag_open']   = '<li class="last">';
$config['last_tag_close']  = '</li>';
$config['next_link']       = '';
$config['next_tag_open']   = '<li class="next">';
$config['next_tag_close']  = '</li>';
$config['prev_link']       = '';
$config['prev_tag_open']   = '<li class="prev">';
$config['prev_tag_close']  = '</li>';
$config['cur_tag_open']    = '<li class="active"><a>';
$config['cur_tag_close']   = '</a></li>';
$config['num_tag_open']    = '<li>';
$config['num_tag_close']   = '</li>';